services:
  # Netdata with full host visibility
  netdata:
    image: netdata/netdata:v2.6.3
    container_name: netdata
    restart: unless-stopped
    pid: "host"
    network_mode: "host"
    cap_add:
      - SYS_PTRACE
      - SYS_ADMIN
    security_opt:
      - apparmor=unconfined
    volumes:
      # Netdata state/config
      - netdata-config-volume:/etc/netdata
      - netdata-lib-volume:/var/lib/netdata
      - netdata-cache-volume:/var/cache/netdata

      # Host mounts (read-only)
      - type: bind
        source: /
        target: /host/root
        read_only: true
        bind:
          propagation: rslave
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /etc/localtime:/etc/localtime:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
      - /var/log:/host/var/log:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /run/dbus:/run/dbus:ro

  # Sidecar that nginx-proxy will discover; forwards to host:19999
  netdata-vhost:
    image: alpine/socat:1.8.0.3
    container_name: netdata-vhost
    command: ["-d","-d","TCP-LISTEN:19999,fork,reuseaddr","TCP:host.docker.internal:19999"]
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=netdata.emilhornlund.com
      - VIRTUAL_PORT=19999
      - LETSENCRYPT_HOST=netdata.emilhornlund.com
    expose:
      - "19999"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - core-network

volumes:
  netdata-config-volume:
    name: netdata-config-volume
  netdata-lib-volume:
    name: netdata-lib-volume
  netdata-cache-volume:
    name: netdata-cache-volume

networks:
  core-network:
    external: true
