services:
  quiz-service:
    image: 192.168.0.65:9500/emilhornlund/quiz-service:baf99fa
    container_name: quiz-service
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - SERVER_PORT=8080
      - SERVER_ALLOW_ORIGIN=https://quiz.emilhornlund.com
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - MONGODB_HOST=mongodb
      - MONGODB_PORT=27017
      - MONGODB_DB=klurigo_prod
      - MONGODB_USERNAME=${MONGODB_USERNAME}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - PEXELS_API_KEY=${PEXELS_API_KEY}
      - UPLOAD_DIRECTORY=/uploads
    volumes:
      - quiz-service-uploads-volume:/uploads
    networks:
      - core-network

volumes:
  quiz-service-uploads-volume:
    name: quiz-service-uploads-volume

networks:
  core-network:
    external: true
