services:
  cloudflare-ddns:
    image: favonia/cloudflare-ddns:1.15.1
    container_name: cloudflare-ddns
    restart: unless-stopped
    network_mode: host
    user: "1000:1000"
    read_only: true
    cap_drop: [all]
    security_opt: [no-new-privileges:true]
    environment:
      CLOUDFLARE_API_TOKEN: ${CLOUDFLARE_API_TOKEN}
      DOMAINS: "emilhornlund.com,klurigo.com"
      PROXIED: "true"
      IP6_PROVIDER: none
