services:
  quiz:
    image: 192.168.0.65:9500/emilhornlund/quiz:baf99fa
    container_name: quiz
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - QUIZ_SERVICE_PROXY=http://quiz-service:8080/api
      - QUIZ_SERVICE_IMAGES_PROXY=http://quiz-service:8080/uploads/images
      - VIRTUAL_HOST=quiz.emilhornlund.com
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=quiz.emilhornlund.com
    networks:
      - core-network

networks:
  core-network:
    external: true
