services:
  pihole:
    image: pihole/pihole:2025.05.1
    container_name: pihole
    restart: unless-stopped
    dns:
      - 127.0.0.1
      - 1.1.1.1
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    environment:
      - TZ=Europe/Stockholm
      - FTLCONF_webserver_api_password=${PIHOLE_PASSWORD}
      - FTLCONF_dns_listeningMode=all
      - FTLCONF_dns_upstreams=8.8.8.8;8.8.4.4
      - FTLCONF_misc_etc_dnsmasq_d=true
      - VIRTUAL_HOST=pihole.emilhornlund.com
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=pihole.emilhornlund.com
    volumes:
      - pihole-etc-volume:/etc/pihole
      - pihole-dnsmasq-volume:/etc/dnsmasq.d
    networks:
      core-network:
        ipv4_address: 172.20.0.11
    cap_add:
      - NET_ADMIN

volumes:
  pihole-dnsmasq-volume:
    name: pihole-dnsmasq-volume
  pihole-etc-volume:
    name: pihole-etc-volume

networks:
  core-network:
    external: true
